name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: get cluster in default namespace    
        run: doctl kubernetes cluster list
      - name: genreta kubeconfig
        run: doctl kubernetes cluster kubeconfig save k8s-1-19-3-do-3-fra1-1611675792046
      - name: show context
        run: kubectl config get-contexts
      - name: get pods
        run: kubectl get pods
